export enum BaseInjectEnum {
    DATABASE_CONTEXT = 'DATABASE_CONTEXT',
    DATA_SOURCE = 'DATA_SOURCE',
    LOGGER = 'LOGGER'
}

export enum UseCaseEnum {
    CREATE_RECEIPT = 'CREATE_RECEIPT',
    FIND_ONE_RECEIPT = 'FIND_ONE_RECEIPT',
    DELETE_ONE_RECEIPT = 'DELETE_ONE_RECEIPT'
}